name: Get Newest Version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 */3 * *"

jobs:
  get-version:
    name: Get Newest Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set variables
        id: set_vars
        run: |
          RELEASE_NAME="Released on $(date +%Y%m%d%H%M)"

          echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_OUTPUT

      - name: Get Version
        run: |
          version=$(curl https://pkg.zeroteam.top/PortForwardGo/latest_version)
          echo $version > version

      - name: Git push assets to branch
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add version
          git commit -m "${{ steps.set_vars.outputs.RELEASE_NAME }}" || true
          git push
